"""Database creation

Revision ID: c930650b18fa
Revises: 
Create Date: 2023-08-03 07:41:06.752064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c930650b18fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hubs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('publication_date', sa.DateTime(), nullable=False),
        sa.Column('link', sa.String(), nullable=False),
        sa.Column('author_name', sa.String(), nullable=False),
        sa.Column('author_link', sa.String(), nullable=False),
        sa.Column('hub_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('hubs')
    # ### end Alembic commands ###
